### ISSUE TITLE
How can I update did:ebsi document ?

### ISSUE THREAD

**Issue by suatbayir1** [decentralized-identity/universal-registrar#40] opened 2021-11-17 15:18 UTC
I want to update the did document that I created using the did:ebsi driver. But I don't know where to get the private key. How can I update an existing did document using the interface on https://uniregistrar.io/ and where can I get the private key?

**Comment by azuzi** [comment] 2021-11-17 16:14
@suatbayir1, we are working on fixing the bug in the update feature.

The private key should be with yourself to update the DID (you should prove the ownership of the DID by holding the private key and using uniregistrar.io for did registration you will get the private key in "keys" )

More about update the Did Document refer here: https://github.com/decentralized-identity/universal-registrar/issues/39

**Comment by azuzi** [comment] 2021-11-17 16:16
Duplicate of #39

**Closed by azuzi** 2021-11-17 16:16 UTC
